name: Unzip, Build, and Commit (dev)

on:
  push:
    branches: [ dev ]
    paths:
      - "**.zip"
  workflow_dispatch:
    inputs:
      zip_file:
        description: 'Path to ZIP in repo (e.g. site.zip). Leave blank to auto-pick newest.'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  unzip-build-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dev   # <- ensure we are actually on dev for manual runs too

      - name: Resolve ZIP to process
        id: resolve
        shell: bash
        run: |
          set -e
          INPUT="${{ github.event.inputs.zip_file }}"

          if [ -n "$INPUT" ]; then
            test -f "$INPUT" || { echo "Provided zip_file not found: $INPUT"; exit 1; }
            echo "zip_path=$INPUT" >> $GITHUB_OUTPUT
            exit 0
          fi

          CHANGED=$(git diff-tree --no-commit-id --name-only -r "$GITHUB_SHA" | grep -E '\.zip$' || true)
          if [ -n "$CHANGED" ]; then
            echo "zip_path=$(echo "$CHANGED" | head -n1)" >> $GITHUB_OUTPUT
            exit 0
          fi

          LATEST=$(git ls-tree -r --name-only HEAD | grep -E '\.zip$' | xargs -r ls -t 2>/dev/null | head -n1 || true)
          if [ -n "$LATEST" ]; then
            echo "zip_path=$LATEST" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "zip_path=" >> $GITHUB_OUTPUT
          echo "No ZIP file found."
          exit 0

      - name: Bail if no zip found
        if: steps.resolve.outputs.zip_path == ''
        run: echo "Nothing to do."

      - name: Unzip to temp and flatten
        if: steps.resolve.outputs.zip_path != ''
        id: unzip
        shell: bash
        run: |
          set -e
          ZIP="${{ steps.resolve.outputs.zip_path }}"
          echo "Processing ZIP: $ZIP"

          rm -rf _unzipped _unzipped_flat
          mkdir -p _unzipped
          unzip -q "$ZIP" -d _unzipped

          # Flatten if a single top-level folder
          DIRS=$(find _unzipped -mindepth 1 -maxdepth 1 -type d | wc -l)
          FILES=$(find _unzipped -mindepth 1 -maxdepth 1 -type f | wc -l)
          if [ "$DIRS" -eq 1 ] && [ "$FILES" -eq 0 ]; then
            INNER=$(find _unzipped -mindepth 1 -maxdepth 1 -type d)
            mv "$INNER" _unzipped_flat
            SRC="_unzipped_flat"
          else
            SRC="_unzipped"
          fi
          echo "src_dir=$SRC" >> $GITHUB_OUTPUT
          echo "Flattened source: $SRC"
          ls -la "$SRC" || true

      - name: Sync extracted content into repo root (overwrite-safe)
        if: steps.unzip.outputs.src_dir != ''
        shell: bash
        run: |
          set -e
          SRC="${{ steps.unzip.outputs.src_dir }}"
          echo "Syncing from: $SRC"

          set +e
          rsync -a --delete \
            --exclude='.git/' \
            --exclude='.github/' \
            --exclude='*.zip' \
            "$SRC"/ ./ 
          code=$?
          set -e

          # ignore "vanished files" (24), fail otherwise
          if [ "$code" -ne 0 ] && [ "$code" -ne 24 ]; then
            echo "rsync failed with code $code"
            exit "$code"
          fi

          rm -rf _unzipped _unzipped_flat || true

      - name: Show changes (debug)
        shell: bash
        run: |
          echo "---- git status ----"
          git status
          echo "---- diff summary ----"
          git --no-pager diff --stat || true

      - name: Setup Node (only if package.json exists)
        if: hashFiles('package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        if: hashFiles('package.json') != ''
        run: npm ci || npm install

      - name: Build assets (supports build:css or build)
        if: hashFiles('package.json') != ''
        shell: bash
        run: |
          if npm run | grep -qE '^ *build:css'; then
            npm run build:css
          elif npm run | grep -qE '^ *build'; then
            npm run build
          else
            echo "No build script found — skipping."
          fi

      # If your .gitignore hides built files, force-add them here (uncomment):
      # - name: Force-add build outputs
      #   run: |
      #     git add -f css/main.css || true

      - name: Commit back to dev
        shell: bash
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Don't re-add zips
          git add -A
          git reset -- $(git ls-files -- '*.zip') 2>/dev/null || true

          echo "---- post-add diff summary ----"
          git --no-pager diff --cached --stat || true

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Unzip + sync + build from ${{ steps.resolve.outputs.zip_path }} [skip ci]"
          git push origin dev
